apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-runtime

components:
- ../components/coding-worker

resources:
- namespace.yaml
- secrets.yaml
- deployment.yaml
- worker-deployment.yaml
- service.yaml
- console-deployment.yaml
- console-service.yaml
- console-ingress.yaml

images:
- name: ghcr.io/helpin-ai/agent-runtime
  newName: ghcr.io/helpin-ai/agent-runtime
  newTag: v0.10.6
- name: ghcr.io/helpin-ai/agent-runtime-coding
  newName: ghcr.io/helpin-ai/agent-runtime-coding
  newTag: v0.11.0-rc.1
- name: ghcr.io/helpin-ai/agent-runtime-console
  newName: ghcr.io/helpin-ai/agent-runtime-console
  newTag: v0.10.6
