apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-runtime-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-agent-runtime-api
  target:
    name: agent-runtime-secrets
  dataFrom:
    - find:
        path: ""
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-helpin-json-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: ghcr-helpin-json-key
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths": { "ghcr.io": {"username": "{{ .GITHUB_HELPIN_USERNAME }}","auth": "{{ (printf "%s:%s" .GITHUB_HELPIN_USERNAME .GITHUB_HELPIN_PAT) | b64enc }}" } } }'
  data:
    - secretKey: GITHUB_HELPIN_PAT
      remoteRef:
        key: GITHUB_HELPIN_PAT
    - secretKey: GITHUB_HELPIN_USERNAME
      remoteRef:
        key: GITHUB_HELPIN_USERNAME
