/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as RunsNewRouteImport } from './routes/runs.new'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as AgentsAgentIdEditRouteImport } from './routes/agents.$agentId.edit'
import { Route as ApiRunsRunIdEventsRouteImport } from './routes/api.runs.$runId.events'

const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdEditRoute = AgentsAgentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const ApiRunsRunIdEventsRoute = ApiRunsRunIdEventsRouteImport.update({
  id: '/api/runs/$runId/events',
  path: '/api/runs/$runId/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/api/health': typeof ApiHealthRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/new': typeof RunsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/api/runs/$runId/events': typeof ApiRunsRunIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/api/health': typeof ApiHealthRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/new': typeof RunsNewRoute
  '/agents': typeof AgentsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/api/runs/$runId/events': typeof ApiRunsRunIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/api/health': typeof ApiHealthRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/new': typeof RunsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/api/runs/$runId/events': typeof ApiRunsRunIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/agents/$agentId'
    | '/agents/new'
    | '/api/health'
    | '/runs/$runId'
    | '/runs/new'
    | '/agents/'
    | '/runs/'
    | '/agents/$agentId/edit'
    | '/api/runs/$runId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/agents/$agentId'
    | '/agents/new'
    | '/api/health'
    | '/runs/$runId'
    | '/runs/new'
    | '/agents'
    | '/runs'
    | '/agents/$agentId/edit'
    | '/api/runs/$runId/events'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/agents/$agentId'
    | '/agents/new'
    | '/api/health'
    | '/runs/$runId'
    | '/runs/new'
    | '/agents/'
    | '/runs/'
    | '/agents/$agentId/edit'
    | '/api/runs/$runId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsNewRoute: typeof RunsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  ApiRunsRunIdEventsRoute: typeof ApiRunsRunIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/edit': {
      id: '/agents/$agentId/edit'
      path: '/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof AgentsAgentIdEditRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/api/runs/$runId/events': {
      id: '/api/runs/$runId/events'
      path: '/api/runs/$runId/events'
      fullPath: '/api/runs/$runId/events'
      preLoaderRoute: typeof ApiRunsRunIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdEditRoute: typeof AgentsAgentIdEditRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdEditRoute: AgentsAgentIdEditRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
  ApiHealthRoute: ApiHealthRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsNewRoute: RunsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  ApiRunsRunIdEventsRoute: ApiRunsRunIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
